### ISSUE TITLE
Ability to start player from parent component

### ISSUE THREAD

**Issue by lmartins** [Blocklevel/vue-media-embed#5]
Would be lovely to have the ability to control video playback from a parent component. The use case is for example when we have the video window inside a modal. Frequently we want the modal to open and automatically start the video. Same goes for when the modal is closed, really useful to have it automatically stop the video too.

Thanks again!

**Comment by supr3m0** [comment]
hiya @lmartins, if you use a v-if, like <vue-media-embed v-if="showVideo" ..... /> and toggle it to show or hide the video, the video will pause/stop automatically and will store the current position of the video. when the video is shown again (showVideo = true) the state  and position of the video will be restored . I assume that you are using a v-show now instead

**Comment by lmartins** [comment]
@supr3m0 that is awesome. I will test this out and comment/close as soon as I get to it (later today hopefully). Thanks again for all the help ;)

**Comment by lmartins** [comment]
@supr3m0 just to confirm this does do the trick. Thanks man!
It would still be nice to have a way to control playback from an outside component, while keeping the video visible, but for the use case I was looking for in particular this works really well. 

Cheers!

**Comment by supr3m0** [comment]
@lmartins awesome, thx for letting me know.  working on a version where you can easily do that, will let you know

**Comment by lmartins** [comment]
@supr3m0 those are really great new news, thank you :)
